name: "Spotcast Custom"
version: "2.0.2"
slug: spotify_chromecast_custom
description: "Custom Spotify Chromecast controller for Home Assistant"
url: "https://github.com/darkkatarsis/spotcast-custom"
icon: "mdi:spotify"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
ports:
  8000/tcp: 8000
options:
  spotify_client_id: ""
  spotify_client_secret: ""
  spotify_redirect_uri: "http://localhost:8000/callback"
  device_name: ""
schema:
  spotify_client_id: str
  spotify_client_secret: str
  spotify_redirect_uri: str
  device_name: str?